### PR TITLE
Add more config variables

### PR DESCRIPTION
**Pull request by Bierchermuesli**
Let me know if any PR is welcome. 

These config values were important to me so i set it as a variable: 

- inet_interfaces
- inet_protocols
- compatibility_level

Maybe considering to rise the default value for `compatibility_level`  in the near future to avoid any technical dept. 

Also I added some Tasks conditions to avoid empty lists if the maps aren't in use.

### CODE REVIEW

**Comment by tboerger** [comment]
Thanks so far, I'm open for contributions. Please do not edit the README manually, this will be overwritten by ansible-doctor after merging the PR. For proper documentation of the attributes please look at the other defaults or https://ansible-doctor.geekdocs.de/usage/getting-started/#annotations.

As you can already see on the PR status I'm expecting [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/), based on that we are generating changelogs and releases automatically.

Some nitpicking from my side, I'm always putting the `when:` attribute above the resource.

**Comment by Bierchermuesli** [comment]
Thanks. didn't know about the ansible-doctor ansd conventional commits 👍 
Do I have to redo the PR for the commit messages?

I also replaced the package loop with a configurable list (which would be best practice), so we can limit the packages if some are not needed.

**Comment by tboerger** [comment]
You can also squash your commits and git push --force them to apply conventional commits.

**Comment by tboerger** [comment]
I have taken your commits and changed them a little bit. Thanks for your effort, much appreciated!

**Comment by tboerger** [comment]
The release 2.1.0 includes your changes, thanks again!

**Pull request closed without merging**
